#!/bin/sh

PROJECT_PATH=$(dirname "$(dirname "$(readlink -f "$0")")")
SCRIPTS_PATH=$(dirname "$(readlink -f "$0")")

pnpm install
ln -sf "$SCRIPTS_PATH/pre-commit" "$PROJECT_PATH/.git/hooks/pre-commit"
